extends:
  - react-app
overrides:
  - files: ["**/*.ts?(x)"]
    extends:
      - react-app
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
    plugins:
      - "@typescript-eslint"
      - "unused-imports"
    parser: "@typescript-eslint/parser"
    rules:
      indent: "off"
      "@typescript-eslint/indent":
        - error
        - 2
        - ignoredNodes:
            - JSXAttribute
            - JSXSpreadAttribute
          ObjectExpression: 1
          SwitchCase: 1
          VariableDeclarator: 2
          MemberExpression: 1
          CallExpression:
            arguments: 1
          FunctionExpression:
            body: 1
            parameters: 1
      quotes: "off"
      "@typescript-eslint/ban-types": "off"
      "@typescript-eslint/quotes": ["error", "single"]
      brace-style: "off"
      "@typescript-eslint/brace-style":
        - error
        - 1tbs
        - allowSingleLine: true
      "@typescript-eslint/camelcase": "off"
      "@typescript-eslint/member-delimiter-style": "off"
      "@typescript-eslint/explicit-function-return-type": "off"
      "@typescript-eslint/no-inferrable-types": "warn"
      "@typescript-eslint/no-unused-vars": "warn"
      "@typescript-eslint/explicit-module-boundary-types": "off"
      "no-console":
        - error
        - allow: ["error"]
      "react-hooks/exhaustive-deps": "error"
      "unused-imports/no-unused-imports-ts": "warn"
